swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: '<script>alert(1)</script>'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
